[project]
name = "certificast"
version = "1.0.0"
description = ""
readme = "README.md"
authors = [
    { name = "wate", email = "ryan.o2712@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2,<3",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "python-pptx>=1.0.2",
    "ruff>=0.16.7",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
